services:
  base:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src/:/app/src/
      - ./data/:/app/data/
      - ./experiments/:/app/experiments/
      - ./models/:/app/models/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  inference:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src/:/app/src/
      - ./data/:/app/data/
      - ./experiments/:/app/experiments/
      - ./models/:/app/models/
      - ./example_payloads/:/app/example_payloads/
      - ./tests/:/app/tests/
    environment:
      - INFERENCE_JSON_PATH=/app/example_payloads/inference.json
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: ["uv", "run", "-m", "tests.inference"]
